server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    # Notice the 5433 port we fixed earlier!
    url: jdbc:postgresql://localhost:5436/orders_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Auto-creates your database tables for this learning project
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # Tells Spring it's safe to deserialize our com.example classes
